// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brand_kits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrandKit = `-- name: CreateBrandKit :one
INSERT INTO brand_kits (
  name,
  colors_json,
  rules_text,
  logo_url
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, colors_json, rules_text, logo_url, created_at, updated_at
`

type CreateBrandKitParams struct {
	Name       string      `json:"name"`
	ColorsJson []byte      `json:"colors_json"`
	RulesText  pgtype.Text `json:"rules_text"`
	LogoUrl    pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateBrandKit(ctx context.Context, arg CreateBrandKitParams) (BrandKit, error) {
	row := q.db.QueryRow(ctx, createBrandKit,
		arg.Name,
		arg.ColorsJson,
		arg.RulesText,
		arg.LogoUrl,
	)
	var i BrandKit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorsJson,
		&i.RulesText,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandKit = `-- name: GetBrandKit :one
SELECT id, name, colors_json, rules_text, logo_url, created_at, updated_at FROM brand_kits
WHERE id = $1
`

func (q *Queries) GetBrandKit(ctx context.Context, id pgtype.UUID) (BrandKit, error) {
	row := q.db.QueryRow(ctx, getBrandKit, id)
	var i BrandKit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorsJson,
		&i.RulesText,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrandKits = `-- name: ListBrandKits :many
SELECT id, name, colors_json, rules_text, logo_url, created_at, updated_at FROM brand_kits
ORDER BY created_at DESC
`

func (q *Queries) ListBrandKits(ctx context.Context) ([]BrandKit, error) {
	rows, err := q.db.Query(ctx, listBrandKits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BrandKit
	for rows.Next() {
		var i BrandKit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ColorsJson,
			&i.RulesText,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
