// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BrandKit struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	ColorsJson []byte             `json:"colors_json"`
	RulesText  pgtype.Text        `json:"rules_text"`
	LogoUrl    pgtype.Text        `json:"logo_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProductImage struct {
	ID         pgtype.UUID        `json:"id"`
	BrandKitID pgtype.UUID        `json:"brand_kit_id"`
	ImageUrl   string             `json:"image_url"`
	ImageName  pgtype.Text        `json:"image_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
