// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_image.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (
  brand_kit_id,
  image_url,
  image_name
) VALUES (
  $1, $2, $3
)
RETURNING id, brand_kit_id, image_url, image_name, created_at
`

type CreateProductImageParams struct {
	BrandKitID pgtype.UUID `json:"brand_kit_id"`
	ImageUrl   string      `json:"image_url"`
	ImageName  pgtype.Text `json:"image_name"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage, arg.BrandKitID, arg.ImageUrl, arg.ImageName)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.BrandKitID,
		&i.ImageUrl,
		&i.ImageName,
		&i.CreatedAt,
	)
	return i, err
}

const listProductImagesForBrandKit = `-- name: ListProductImagesForBrandKit :many
SELECT id, brand_kit_id, image_url, image_name, created_at FROM product_images
WHERE brand_kit_id = $1
ORDER BY created_at
`

func (q *Queries) ListProductImagesForBrandKit(ctx context.Context, brandKitID pgtype.UUID) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImagesForBrandKit, brandKitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.BrandKitID,
			&i.ImageUrl,
			&i.ImageName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
